### PR TITLE
lib: upnp, netroute, unmap port on exit

### PR DESCRIPTION
**Pull request by indutny**
nt

### CODE REVIEW

**Comment by indutny** [comment]
so?

**Comment by Marak** [comment]
Working on it. I have pressing commits with Flatiron first.

Sorry for the delay, will get to it soon.

I can just add you as admin if that would be easier.

**Comment by Marak** [comment]
@indutny - Did you test this?

I'm seeing badly formatted output in command line. Also, upon CTRL-C of `natman`, the ports still stay open. I had assumed this pull request would also fix that.

``` bash
~/dev/natman/natman open 8080 8008
info:    Creating NAT...
warn:    Using gateway: 10.0.1.1
help:    You can manually specify a gateway with -g argument
warn:    Attempting to connect... 
info:    Connected to WAN address: 7119876200
warn:    Mapping 7119876200:8008 => localhost:8080
info:    NAT established.
info:    Press CTRL-C to stop the NAT...
^C~/dev/natman/

```

**Comment by Marak** [comment]
@indutny - I fixed the minor formatting issue, but it appears that the NAT won't close unless you CTRL-C natman, and then restart the service. Is that expected?

**Pull request merged**
